version: "3.0"

services:
  web:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - "~/data/dbharat-movies/uploads:/uploads:rw"
    environment:
      - PORT:80
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    env_file:
      - .env
    restart: always
    volumes:
      - "~/data/dbharat-movies/db:/var/lib/mysql"
    expose:
      - 3306

  redis:
    image: redis:6
    restart: always
    expose:
      - 6379
